version: '3'
services:
  wildbeast:
    image: .
    env_file:
      - .env
    links:
    - lavalink
    depends_on:
      - lavalink
      - install
  lavalink:
    image: fredboat/lavalink:master-v3
    env_file:
      - lavalink.env
